# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e89eea8d6d29e6a2d6c0cdef2272d12c477fdc0c4307964c8af7b2b9fe3a3f41d063eee413cccee3453b117e8881b5b2fd64b224d356ab4b4320be1f2c21dcc

test:
  secret_key_base: efff43cbc5e20209f01c3b611506176cce8a77bc3d3d28d4e9a6e11e76f2228b2b2f3c6ce902cc23366d76aad14d5d56b782e44df6cacbc5edac07b25ac0c576

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
